name: 'SWM: Deploy to Azure'

on:
  push:
    branches:
    - main

jobs:
  call_build_test:
    uses: justinyoo/swm-gha-workshop-adv/.github/workflows/build-test.yaml@main
    with:
      job_name: 'Build and Test for main'
      app_location: api

  call_deploy_azure_dev:
    uses: justinyoo/swm-gha-workshop-adv/.github/workflows/deploy-azure.yaml@main
    needs: call_build_test
    with:
      job_name: 'Deploy to Azure DEV'
      environment: 'dev'
    secrets:
      azure_credentias: ${{ secrets.AZURE_CREDENTIALS }}
      resource_name: ${{ secrets.RESOURCE_NAME }}

  call_deploy_azure_prod:
    uses: justinyoo/swm-gha-workshop-adv/.github/workflows/deploy-azure.yaml@main
    needs: call_deploy_azure_dev
    with:
      job_name: 'Deploy to Azure PROD'
      environment: 'prod'
    secrets:
      azure_credentias: ${{ secrets.AZURE_CREDENTIALS }}
      resource_name: ${{ secrets.RESOURCE_NAME }}
